### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by navanchauhan**

### CODE REVIEW

**Comment by navanchauhan** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
Zblerg I'm confused about why the tests are failing ... with this `UI` thingy in the url somehow ?

Sounds like there's an issue maybe related to the BasePathOverride thingy in the install script ? https://github.com/YunoHost-Apps/jackett_ynh/blob/master/scripts/install#L111

**Comment by Salamandar** [comment]
@alexAubin well i installed it locally, and it works fine, no weird redirect to https://UI/…

**Comment by Salamandar** [comment]
Will (at least) partially be fixed by https://github.com/YunoHost/package_check/pull/154

**Pull request merged**
